-- vhdl file of block altera generated by Agravic
library ieee;use ieee.std_logic_1164.all;use IEEE.NUMERIC_STD.ALL;

package altera is




component clk_gating_cell is
        port (
            inclk : in std_logic := 'X'; -- inclk
            ena : in std_logic := 'X'; -- ena
            outclk : out std_logic -- outclk
        );
end component clk_gating_cell;



end altera;
