-- vhdl file of block peripherals generated by Agravic
library ieee;use ieee.std_logic_1164.all;use IEEE.NUMERIC_STD.ALL;
library work; use work.structures.all;
entity peripherals is port( clk_peri : IN std_logic; reset_n : IN std_logic; core2mem_i : IN blk2mem_t; gpios_o : OUT unsigned ((32 -1) downto 0) ); end peripherals; architecture rtl of peripherals is component dummy_zkw_pouet is port(clk : in std_logic);end component;
begin
process0 : process(clk_peri,reset_n)
begin
 IF ( reset_n = '0' ) then
 gpios_o <= TO_UNSIGNED(0,32);
 elsif ( clk_peri'event and (clk_peri = '1' ) ) then
  IF ( ( core2mem_i.cs_n = '0' ) and ( core2mem_i.wr_n = '0' ) ) then
   IF (core2mem_i.addr = "1111111111111") then
    gpios_o <= core2mem_i.data;
   end if;
  end if;
 end if;
end process;
end rtl;
