-- vhdl file of block structures generated by Agravic
library ieee;use ieee.std_logic_1164.all;use IEEE.NUMERIC_STD.ALL;
package structures is
type blk2mem_t is record addr : unsigned ((13 -1) downto 0); data : unsigned ((32 -1) downto 0); be : unsigned ((4 -1) downto 0); cs_n : std_logic; wr_n : std_logic; end record;
type mem2blk_t is record data : unsigned ((32 -1) downto 0); data_en : std_logic; end record;
end structures;
