-- vhdl file of block tb generated by Agravic
library ieee;use ieee.std_logic_1164.all;use IEEE.NUMERIC_STD.ALL;
library work; use work.structures.all;
entity tb_t is ); end tb_t; architecture rtl of tb_t is component dummy_zkw_pouet is port(clk : in std_logic);end component;
constant c_clock_period : time := 5 ns;
constant c_reset_length : time := 20 ns;
signal clk : std_logic;
signal reset_n : std_logic;
begin
gen_clk: process
begin
   wait for (c_clock_period / 2);
   clk <= not clk;
end process gen_clk;
gen_reset_n: process
begin
   wait for c_reset_length;
   reset_n <= '1';
   wait;
end process gen_reset_n;
end rtl;
