-- vhdl file of block risc-V_core generated by Agravic
library ieee;use ieee.std_logic_1164.all;use IEEE.NUMERIC_STD.ALL;
library work; use work.structures.all;
entity top is port( clk : IN std_logic; reset_n : IN std_logic; load_port_i : IN blk2mem_t; gpios_o : OUT unsigned ((32 -1) downto 0) ); end top; architecture rtl of top is component dummy_zkw_pouet is port(clk : in std_logic);end component;
component risc_V_core is port( clk : IN std_logic; reset_n : IN std_logic; load_port_i : IN blk2mem_t; core2instmem_o : OUT blk2mem_t; instmem2core_i : IN mem2blk_t; core2datamem_o : OUT blk2mem_t; datamem2core_i : IN mem2blk_t ); end component;
component mem is port( clk : IN std_logic; reset_n : IN std_logic; core2mem_i : IN blk2mem_t; mem2core_o : OUT mem2blk_t ); end component;
component peripherals is port( clk : IN std_logic; reset_n : IN std_logic; core2mem_i : IN blk2mem_t; gpios_o : OUT unsigned ((32 -1) downto 0) ); end component;
signal core2instmem : blk2mem_t;
signal instmem2core : mem2blk_t;
signal core2datamem : blk2mem_t;
signal datamem2core : mem2blk_t;
signal instmem_cs_n : std_logic;
signal instmem_wr_n : std_logic;
signal datamem_cs_n : std_logic;
signal datamem_wr_n : std_logic;
begin
u0_risc_V_core : risc_V_core port map( clk => clk, reset_n => reset_n, load_port_i => load_port_i, core2instmem_o => core2instmem, instmem2core_i => instmem2core, core2datamem_o => core2datamem, datamem2core_i => datamem2core);
u0_mem : mem port map( clk => clk, reset_n => reset_n, core2mem_i => core2instmem, mem2core_o => instmem2core);
u1_mem : mem port map( clk => clk, reset_n => reset_n, core2mem_i => core2datamem, mem2core_o => datamem2core);
u0_peripherals : peripherals port map( clk => clk, reset_n => reset_n, core2mem_i => core2datamem, gpios_o => gpios_o);
end rtl;
